---
- name: Install radvd
  dnf:
    name: radvd

- name: Template config file
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf

- name: Start and enable radvd
  systemd:
    name: radvd
    state: restarted
    enabled: yes
    daemon_reload: yes
